{
    "name": "Керування орендою автомобілів",
    "summary": "Автомобілі, бронювання, огляди та пошкодження",
    "version": "19.0.1.0.0",
    "category": "Services/Rental",
    "author": "xvbeb",
    "license": "AGPL-3",
    "depends": ["contacts", "product"],
    "data": [
        "security/ir.model.access.csv",
        "views/res_partner_views.xml",
        "views/product_template_views.xml",
        "views/car_rental_vehicle_category_views.xml",
        "views/car_rental_location_views.xml",
        "views/car_rental_vehicle_views.xml",
        "views/car_rental_booking_views.xml",
        "views/car_rental_inspection_views.xml",
        "views/car_rental_damage_views.xml",
        "wizard/car_rental_booking_extend_wizard_views.xml",
        "views/car_rental_menus.xml",
    ],
    "application": True,
    "installable": True,
}
